[workspace]
members = [
    "bin/reth",
    "crates/consensus/auto-seal",
    "crates/consensus/beacon",
    "crates/consensus/common",
    "crates/executor",
    "crates/interfaces",
    "crates/miner",
    "crates/metrics/metrics-derive",
    "crates/metrics/common",
    "crates/net/common",
    "crates/net/ecies",
    "crates/net/eth-wire",
    "crates/net/discv4",
    "crates/net/dns",
    "crates/net/nat",
    "crates/net/network-api",
    "crates/net/network",
    "crates/net/downloaders",
    "crates/primitives",
    "crates/revm",
    "crates/revm/revm-primitives",
    "crates/revm/revm-inspectors",
    "crates/rlp",
    "crates/rlp/rlp-derive",
    "crates/rpc/ipc",
    "crates/rpc/rpc",
    "crates/rpc/rpc-api",
    "crates/rpc/rpc-builder",
    "crates/rpc/rpc-engine-api",
    "crates/rpc/rpc-types",
    "crates/staged-sync",
    "crates/stages",
    "crates/storage/codecs",
    "crates/storage/db",
    "crates/storage/libmdbx-rs",
    "crates/storage/libmdbx-rs/mdbx-sys",
    "crates/storage/provider",
    "crates/tracing",
    "crates/tasks",
    "crates/transaction-pool",
    "crates/trie",
]
exclude = ["crate-template"]
default-members = ["bin/reth"]

# Like release, but with full debug symbols. Useful for e.g. `perf`.
[profile.debug-fast]
inherits = "release"
debug = true

[patch.crates-io]
revm = { git = "https://github.com/layer-g/revm", branch = "tan" }
revm-primitives = { git = "https://github.com/layer-g/revm", branch = "tan" }
# patched for quantity U256 responses <https://github.com/recmo/uint/issues/224>
# ruint = { git = "https://github.com/paradigmxyz/uint" }
