version: '3.9'
name: 'lattice'

services:
  reth:
    restart: unless-stopped
    # image: us-docker.pkg.dev/telcoin-network/telcoin-network/lattice:latest
    image: layerg/auto-seal:latest
    ports:
      - '9001:9001' # metrics
      - '8545:8545' # rpc
      - '8551:8551' # engine
    volumes:
      - rethdata_lattice:/root/.local/share/reth/2600/db
      # - rethdata_sepolia:/root/.local/share/reth/sepolia/db
      - rethlogs:/root/rethlogs
      # - ./jwttoken:/root/jwt:ro
    command: >
      lattice --dev 
      --metrics 0.0.0.0:9001
      --http --http.addr 0.0.0.0
      --http.port 8545
      --http.api "eth,net,web3"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus
    depends_on:
      - reth
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheusdata:/prometheus
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.external-url=http://localhost:9090/graph

  grafana:
    restart: unless-stopped
    image: grafana/grafana:10.1.0
    depends_on:
      - reth
      - prometheus
    ports:
      - 3000:3000
    environment:
      PROMETHEUS_URL: http://prometheus:9090
    volumes:
      - grafanadata:/var/lib/grafana
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./grafana/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/dashboards:/etc/grafana/provisioning_temp/dashboards
    # 1. Copy dashboards from temp directory to prevent modifying original host files
    # 2. Replace Prometheus datasource placeholder with the actual name
    # 3. Run Grafana
    entrypoint: >
      sh -c "cp -r /etc/grafana/provisioning_temp/dashboards/. /etc/grafana/provisioning/dashboards &&
             find /etc/grafana/provisioning/dashboards/ -name '*.json' -exec sed -i 's/$${DS_PROMETHEUS}/Prometheus/g' {} \+ &&
             /run.sh"

volumes:
  rethdata_lattice:
    driver: local
  rethlogs:
    driver: local
  prometheusdata:
    driver: local
  grafanadata:
    driver: local