[package]
name = "reth-mdbx-sys"
version = "0.12.1-0"
edition = "2021"
license = "Apache-2.0"
description = "Rust bindings for libmdbx with good licence."
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"

[lib]
name = "reth_mdbx_sys"

[dependencies]
libc = "0.2"

[build-dependencies]
cc = "1.0"
bindgen = { version = "0.65", default-features = false, features = ["runtime"] }
