[package]
name = "reth-staged-sync"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/paradigmxyz/reth"
readme = "README.md"
description = "Puts together all the Reth stages in a unified abstraction"

[dependencies]
# reth
reth-db = {path = "../../crates/storage/db", features = ["mdbx", "test-utils"] }
reth-discv4 = { path = "../../crates/net/discv4" }
reth-network-api = { path = "../../crates/net/network-api" }
reth-network = { path = "../../crates/net/network", features = ["serde"] }
reth-downloaders = { path = "../../crates/net/downloaders" }
reth-primitives = { path = "../../crates/primitives" }
reth-provider = { path = "../../crates/storage/provider", features = ["test-utils"] }
reth-net-nat = { path = "../../crates/net/nat" }

# io
serde = "1.0"
serde_json = "1.0.91"

# misc
walkdir = "2.3.2"
eyre = "0.6.8"
shellexpand = "3.0.0"
tracing = "0.1.37"

# crypto
rand = { version = "0.8", optional = true }

# errors
thiserror = "1"

# enr
enr = { version = "0.8.0", features = ["serde", "rust-secp256k1"], optional = true }

# ethers
ethers-core = { git = "https://github.com/gakonst/ethers-rs", default-features = false, optional = true }
ethers-providers = { git = "https://github.com/gakonst/ethers-rs", features = ["ws"], default-features = false, optional = true }
ethers-middleware = { git = "https://github.com/gakonst/ethers-rs", default-features = false, optional = true }
ethers-signers = { git = "https://github.com/gakonst/ethers-rs", default-features = false, optional = true }

# async / futures
async-trait = { version = "0.1", optional = true }
tokio = { version = "1", features = ["io-util", "net", "macros", "rt-multi-thread", "time"], optional = true }

# misc
hex = { version = "0.4", optional = true }

[dev-dependencies]
# reth crates
reth-tracing = { path = "../tracing" }
reth-downloaders = { path = "../net/downloaders" }

# async/futures
futures = "0.3"
tokio = { version = "1", features = ["io-util", "net", "macros", "rt-multi-thread", "time"] }

# crypto
secp256k1 = { version = "0.26.0", features = [
    "global-context",
    "rand-std",
    "recovery",
] }

confy = "0.5"

tempfile = "3.4"

[features]
test-utils = [
    "reth-network/test-utils",
    "reth-network/test-utils",
    "reth-provider/test-utils",
    "dep:enr",
    "dep:ethers-core",
    "dep:hex",
    "dep:rand",
    "dep:tokio",
    "dep:ethers-signers",
    "dep:ethers-providers",
    "dep:ethers-middleware",
    "dep:async-trait"
]
